hostname: "http://yourdomain.com"
basepath: ""

title: Finding The Way Home
description: >
  A beautiful narrative written with the world's most elegant
  publishing platform. The story begins here.
cover: "/assets/images/home1.jpg"
logo: "/assets/images/ghost.png"

navigation:
  Home: "/"
  About: "/about/"
  Fables: "/tag/fables/"
  Speeches: "/tag/speeches/"

authors:
  "Edgar Rice Burroughs":
    bio: >
      I'm an American novelist, best known for my work writing about a
      brave jungle hero called Tarzan and his muse, Jane.
    location: "Chicago, Illinois"
  "Martin Luther King":
    image: "/assets/images/mlk.jpg"
  "Nikolai Frits":
    bio: "I share links on writing, publishing & new media."
    image: "/assets/images/avatar2.jpg"
    website: "http://bit.ly/1nP8GsR"
  "Otho Korbin":
    bio: "I am taking full advantage of long summer days and warm weather."
    image: "/assets/images/avatar1.jpg"
    website: "http://bit.ly/1TKGbcn"

tags:
  Fables:
    description: A series of short stories that make you think.
    image: "/assets/images/cover2.jpg"
  Speeches:
    description: Some of the greatest words ever spoken.
    image: "/assets/images/cover1.jpg"
