title: Finding The Way Home
description: >
  A beautiful narrative written with the world's most elegant
  publishing platform. The story begins here.
cover: "assets/images/cover1.jpg"
logo: "assets/images/ghost.png"
navigation: true
