hostname: "http://yourdomain.com"
basepath: ""

title: Finding The Way Home
description: >
  A beautiful narrative written with the world's most elegant
  publishing platform. The story begins here.
cover: "/assets/images/home1.jpg"
logo: "/assets/images/ghost.png"

navigation:
  - title: Home
    path: "/"
  - title: About
    path: "/about/"
  - title: Fables
    path: "/tag/fables/"
  - title: Speeches
    path: "/tag/speeches/"

tags:
  Speeches:
    description: Some of the greatest words ever spoken.
    image: "/assets/images/cover1.jpg"
  Fables:
    description: A series of short stories that make you think.
    image: "/assets/images/cover2.jpg"
